// src/lib/contracts.ts
import { Contract } from 'ethers';
import { getProvider, getSigner } from './hedera';

// Import ABIs generated by Hardhat (copied into frontend/src/abi)
import EscrowArtifact from '../abi/EscrowGame.json';
import OracleArtifact from '../abi/OracleAdapter.json';
import CcipArtifact from '../abi/CCIPReceiver.json';

// Extract the ABI from the artifacts
const EscrowAbi = EscrowArtifact.abi;
const OracleAbi = OracleArtifact.abi;
const CcipAbi = CcipArtifact.abi;

const env = (k: string, d = '') => (import.meta as any)?.env?.[k] ?? d;

const CHAIN_ID_NUM = Number(env('VITE_CHAIN_ID', '296')); // default Hedera testnet

// Fallback addresses for Hedera testnet (chain ID 296)
const FALLBACK_ADDRESSES = {
  'VITE_ESCROW_GAME': '0x3D53EDA80D6552414330CB0876451e04f112661f',
  'VITE_ORACLE_ADAPTER': '0x975776fD9b9E4FbC30e76324a25738dfbC61E292',
  'VITE_CCIP_RECEIVER': '0xd66a95E968c1ED60373a4E11Af9048F1EA60C381',
  'VITE_ESCROW_GAME_296': '0x3D53EDA80D6552414330CB0876451e04f112661f',
  'VITE_ORACLE_ADAPTER_296': '0x975776fD9b9E4FbC30e76324a25738dfbC61E292',
  'VITE_CCIP_RECEIVER_296': '0xd66a95E968c1ED60373a4E11Af9048F1EA60C381',
};

function resolveEnvAddress(key: string, chainId = CHAIN_ID_NUM): string {
  const chainKey = `${key}_${chainId}`;
  const chainVal = env(chainKey);
  const generic = env(key);
  
  if (chainVal && chainVal.trim() !== '') {
    return chainVal as string;
  }
  if (generic && generic.trim() !== '') {
    return generic as string;
  }
  
  // Try fallback addresses
  const fallbackChain = FALLBACK_ADDRESSES[chainKey as keyof typeof FALLBACK_ADDRESSES];
  const fallbackGeneric = FALLBACK_ADDRESSES[key as keyof typeof FALLBACK_ADDRESSES];
  
  if (fallbackChain) {
    return fallbackChain;
  }
  if (fallbackGeneric) {
    return fallbackGeneric;
  }
  
  const errorMsg = `Missing address for ${key}. Set ${chainKey} or ${key} in .env. Current values: chainVal="${chainVal}", generic="${generic}"`;
  throw new Error(errorMsg);
}

function addrOrEnv(userAddr: string | undefined, envKey: string): string {
  return (userAddr && userAddr !== '') ? userAddr : resolveEnvAddress(envKey);
}

/** Thin factory: returns on-demand read/write contract handles */
function factory(abi: any, defaultEnvKey: string) {
  return (address?: string) => {
    const resolved = addrOrEnv(address, defaultEnvKey);

    return {
      address: resolved,
      read(): Contract {
        const p = getProvider();
        return new Contract(resolved, abi, p);
      },
      async write(): Promise<Contract> {
        const s = await getSigner();
        return new Contract(resolved, abi, s);
      },
    };
  };
}

// Public helpers
export const escrow  = factory(EscrowAbi,  'VITE_ESCROW_GAME');
export const oracle  = factory(OracleAbi,  'VITE_ORACLE_ADAPTER');
export const ccip    = factory(CcipAbi,    'VITE_CCIP_RECEIVER');

// Optional: convenience singletons (only if you prefer quick imports)
// export const Escrow = escrow();
// export const Oracle = oracle();
// export const CCIP   = ccip();
